#### Codons

Codons := 'sequences of 3 nucleotides'.

Nucleotides := 'are organic molecules composed of a nitrogenous base(Nucleo Basis), penthose sugar and one phosphate group'.

$
\begin{equation}
 =
    \begin{cases}
       \text{Nucleobasis} & \text{are nitrogen-containing biological compounds that form nucleosides.
       5 nucleobases are called primary or canonical: Adenine(A), Cytosine(C), Guanine(G), Thymine(T), Uracil(U). They function as the fundamental units of the genetic code. } \\
        \text{pentose sugar} & \text{ is a monosaccharide(simple sugar) with five carbon atoms. } \\
        \text{phosphate} & \text{ is an anion, salt, functional group or ester derived from phosphoric acid. Anion -- an ion that has more electrons than protons, giving it a net negative charge(Anion (-)). }\\
    \end{cases}
\end{equation}$

There are 4 types of nucleotides. Codons = _4_  _4_  _4_ = 64 possible codons.

61 of them are called sense codons (meaning, they specify aminoacids)

20 amino acids - but 61 codons that make sense to aminoacids sooo some of them have the same sense.
Example: GCU - alanine - GCA - GCG

3 of them are called stop codons because they give a signal to the ribosome to stop translation.

#### Amino Acids

Amino Acids := 'are organic compunds that contain both amino and carboxilic functional groups.'

Amines := 'are compounds and functional groups that contain a basic nitrogren atom with a lone pair(pair of valence electrones that are not shared with another atom in a covalent bond and is sometimes called an unshared pair.) Amines are formally derivatives of ammonia (NH3), wherein one or more hydrogen atoms have been replaced by a substituent such us an atyl or aryl group. IMPORTANT amines include: amino acids, biogenic amines, trimethylamine and aniline.'

Functional Group := 'is a substituent or moiety(a part of a molecule) in a molecule that causes the molecules characteristics chemical reactions.'

Molecule := 'is a group of two or more atoms held together by attractive forces known as chemical bonds.'

## Protein Folding

Given Two statistical samples X = $\{x_i\}_{i=1}^{N_X}$ and Y = $\{y_i\}_{i=1}^{N_Y}$

We wish to test wether the observations in both samples were obtained from the same underlying data distribution.

In order to avoid making unfounded assumptions about the data or compromising on the choice of test statistics we employed a permutation bases two sample hypothesis test.

### Permutation Test
For independent sample statistics, the null hypothesis is that the data are randomly sampled from the same distribution. For paired sample statistics, two null hypothesis can be tested: that the data are paired at random or that the data are assigned to samples at random.

In [1]:
import numpy as np
from scipy.stats import norm

In [3]:
rng = np.random.default_rng()
print(f'rng: {rng}')

rng: Generator(PCG64)


In [4]:
x = norm.rvs(size=5, random_state=rng)
y = norm.rvs(size=6, loc = 3, random_state=rng)

In [6]:
y

array([4.26754011, 3.31859953, 3.29312458, 1.64846   , 3.40276707,
       3.64523936])

In [7]:
def statistic(x, y, axis):
    return np.mean(x, axis=axis) - np.mean(y, axis=axis)

In [9]:
statistic(x,y,0)

-3.3864418260222346

In [11]:
from scipy.stats import permutation_test

In [13]:
res = permutation_test((x, y), statistic, vectorized=True,n_resamples=np.inf, alternative='less')

In [14]:
print(f'stat:{ res.statistic}')

stat:-3.3864418260222346


In [15]:
print(f'p-value:{ res.pvalue}')

p-value:0.0021645021645021645


Since p-value $= 0.0021 < 0.05 = \alpha$ then there is enough evidence to reject $H_0$ that the samples were selected from the same probability distribution.

### Permutation Test By Hand

https://medium.com/@whystudying/resampling-with-python-permutation-test-19421dc38dac

In [20]:
type(x)
len(x)
np.concatenate((x, y), axis=0)

array([-0.86308853, -0.263746  , -0.61461525, -0.22165073,  1.34400027,
        4.26754011,  3.31859953,  3.29312458,  1.64846   ,  3.40276707,
        3.64523936])

In [22]:
x

array([-0.86308853, -0.263746  , -0.61461525, -0.22165073,  1.34400027])

In [17]:
def permutation_test(x,y,K): # K - Number of perutations
    p_value = 0
    Nx = len(x)
    Ny = len(y)
    # Pool the observations
    Z = np.concatenate((x, y), axis=1)
    pi = 
    return p_value

SyntaxError: invalid syntax (3167449990.py, line 6)

In [24]:
import pandas as pd

In [25]:
# Raw dataset file containing non-redundant structures used for codon distribution analysis.
dataprecs = pd.read_csv('data-precs.csv') 

C:\Users\jesus\AppData\Local\Temp\ipykernel_7164\3181351105.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  dataprecs = pd.read_csv('data-precs.csv')


In [26]:
dataprecs.head()

pdb_id  unp_id res_id name  unp_idx codon  codon_score codon_opts  bfactor  \
0  4IWN:A  P76290     19    T     18.0   ACC          1.0        ACC    40.18   
1  4IWN:A  P76290     20    F     19.0   TTT          1.0        TTT    34.37   
2  4IWN:A  P76290     21    D     20.0   GAT          1.0        GAT    31.49   
3  4IWN:A  P76290     22    E     21.0   GAA          1.0        GAA    30.86   
4  4IWN:A  P76290     23    R     22.0   CGG          1.0        CGG    27.13   

  secondary    phi    psi  
0         -    NaN -34.15  
1         H -58.45 -39.93  
2         H -57.05 -49.49  
3         H -68.28 -34.54  
4         H -71.99 -40.20

In [27]:
dataprecs.shape

(357479, 12)